name: core
description: The core of the ODW SDK.
version: 0.7.6
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/core

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  crypto: '>=2.0.0 <2.1.0'
  path: '>=1.6.0 <2.1.0'
  quiver: '>=2.0.0 <2.1.0'
# TODO before V0.9.0: decide on using pub_semver or version - remove one
  version: ^1.0.2
#  decimal: ^0.3.0
  bytes:
    path: ../bytes
  bytes_dicom:
    path: ../bytes_dicom

dev_dependencies:
  benchmark_harness: any
  coverage: any
  grinder: ^0.8.0
  test:  any
  test_tools:
    path: ../../test_tools
    version: ^0.7.5
  yaml: ^2.1.12
