name: core
description: The core of the ODW SDK.
version: 0.7.0
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/core

environment:
  sdk: '>=1.24.0 <2.0.1'

dependencies:
  bignum: ^0.1.0
  crypto: any
  quiver: any
# TODO before V0.9.0: decide on using pub_semver or version - remove one
  version: ^1.0.2

dev_dependencies:
  test:  any
  benchmark_harness: any
  coverage: any
  grinder: ^0.8.0
  yaml: ^2.1.12
  pub_semver: ^1.3.2
  test_tools:
    path: C:\acr\odw\test_tools
    version: ^0.7.0
