//  Copyright (c) 2016, 2017, 2018,
//  Poplar Hill Informatics and the American College of Radiology
//  All rights reserved.
//  Use of this source code is governed by the open source license
//  that can be found in the odw/LICENSE file.
//  Primary Author: Jim Philbin <jfphilbin@gmail.edu>
//  See the AUTHORS file for other contributors.
//
import 'package:core/src/tag.dart';
import 'package:core/src/tag/private/new_tag/pc_tag_definitions.dart';

// ignore_for_file: public_member_api_docs

PDTagDefinition lookupPCTag(String creatorToken, int pdCode) {
  final pdTags = creatorIdMap[creatorToken];
  return pdTags[pdCode];
}

const Map<String, Map<int, PDTagDefinition>> creatorIdMap =
    const <String, Map<int, PDTagDefinition>>{
  '1.2.840.113681': Uid_1_2_840_113681,
  '1.2.840.113708.794.1.1.2.0': Uid_1_2_840_113708_794_1_1_2_0,
  'ACUSON': ACUSON,
  'AEGIS_DICOM_2.00': AEGIS_DICOM_2_00,
  'AGFA': AGFA,
  'CAMTRONICS IP': CAMTRONICS_IP,
  'CAMTRONICS': CAMTRONICS,
  'CARDIO-D.R. 1.0': CARDIO_D_R__1_0,
  'MRSC': MRSC,
  'CMR42 CIRCLECVI': CMR42_CIRCLECVI,
  'DCMTK_ANONYMIZER': DCMTK_ANONYMIZER,
  'DIDI TO PCR 1.1': DIDI_TO_PCR_1_1,
  'DIGISCAN IMAGE': DIGISCAN_IMAGE,
  'DLX_EXAMS_01': DLX_EXAMS_01,
  'DLX_PATNT_01': DLX_PATNT_01,
  'DLX_SERIE_01': DLX_SERIE_01,
  'ELSCINT1': ELSCINT1,
  'FDMS 1.0': FDMS_1_0,
  'GEMS_PARM_01': GEMS_PARM_01,
  'FFP DATA': FFP_DATA,
  'GE ??? From Adantage Review CS': GE_____From_Adantage_Review_CS,
  'GEMS_ACQU_01': GEMS_ACQU_01,
  'GEMS_ACRQA_1.0 BLOCK1': GEMS_ACRQA_1_0_BLOCK1,
  'GEMS_ACRQA_1.0 BLOCK2': GEMS_ACRQA_1_0_BLOCK2,
  'GEMS_ACRQA_1.0 BLOCK3': GEMS_ACRQA_1_0_BLOCK3,
  'GEMS_ACRQA_2.0 BLOCK1': GEMS_ACRQA_2_0_BLOCK1,
  'GEMS_ACRQA_2.0 BLOCK2': GEMS_ACRQA_2_0_BLOCK2,
  'GEMS_ACRQA_2.0 BLOCK3': GEMS_ACRQA_2_0_BLOCK3,
  'GEMS_ADWSoft_3D1': GEMS_ADWSoft_3D1,
  'GEMS_ADWSoft_DPO': GEMS_ADWSoft_DPO,
  'GEMS_CTHD_01': GEMS_CTHD_01,
  'GEMS_DRS_1': GEMS_DRS_1,
  'GEMS_GENIE_1': GEMS_GENIE_1,
  'GEMS_GNHD_01': GEMS_GNHD_01,
  'GEMS_IDEN_01': GEMS_IDEN_01,
  'GEMS_IMAG_01': GEMS_IMAG_01,
  'GEMS_IMPS_01': GEMS_IMPS_01,
  'GEMS_RELA_01': GEMS_RELA_01,
  'SIEMENS RA GEN': SIEMENS_RA_GEN,
  'GEMS_SENO_02': GEMS_SENO_02,
  'GEMS_YMHD_01': GEMS_YMHD_01,
  'GE_GENESIS_REV3.0': GE_GENESIS_REV3_0,
  'SVISION': SVISION,
  'GEMS_STDY_01': GEMS_STDY_01,
  'GEMS_SERS_01': GEMS_SERS_01,
  'INTELERAD MEDICAL SYSTEMS': INTELERAD_MEDICAL_SYSTEMS,
  'INTEGRIS 1.0': INTEGRIS_1_0,
  'ISG shadow': ISG_shadow,
  'ISI': ISI,
  'MERGE TECHNOLOGIES, INC.': MERGE_TECHNOLOGIES__INC_,
  'OCULUS Optikgeraete GmbH': OCULUS_Optikgeraete_GmbH,
  'PAPYRUS 3.0': PAPYRUS_3_0,
  'PAPYRUS': PAPYRUS,
  'Philips Imaging DD 001': Philips_Imaging_DD_001,
  'Philips MR Imaging DD 001': Philips_MR_Imaging_DD_001,
  'Philips MR Imaging DD 005': Philips_MR_Imaging_DD_005,
  'PHILIPS MR R5.5/PART': PHILIPS_MR_R5_5_PART,
  'PHILIPS MR R5.6/PART': PHILIPS_MR_R5_6_PART,
  'PHILIPS MR SPECTRO;1': PHILIPS_MR_SPECTRO_1,
  'PHILIPS MR': PHILIPS_MR,
  'PHILIPS MR/LAST': PHILIPS_MR_LAST,
  'PHILIPS MR/PART': PHILIPS_MR_PART,
  'PHILIPS-MR-1': PHILIPS_MR_1,
  'Picker NM Private Group': Picker_NM_Private_Group,
  'SIEMENS CM VA0  ACQU': SIEMENS_CM_VA0__ACQU,
  'SIEMENS CM VA0  CMS': SIEMENS_CM_VA0__CMS,
  'SIEMENS CM VA0  LAB': SIEMENS_CM_VA0__LAB,
  'SIEMENS CSA NON-IMAGE': SIEMENS_CSA_NON_IMAGE,
  'SIEMENS CT VA0  COAD': SIEMENS_CT_VA0__COAD,
  'SIEMENS CSA HEADER': SIEMENS_CSA_HEADER,
  'SIEMENS CT VA0  GEN': SIEMENS_CT_VA0__GEN,
  'SIEMENS CT VA0  IDE': SIEMENS_CT_VA0__IDE,
  'SIEMENS CT VA0  ORI': SIEMENS_CT_VA0__ORI,
  'SIEMENS CT VA0  OST': SIEMENS_CT_VA0__OST,
  'SIEMENS CT VA0  RAW': SIEMENS_CT_VA0__RAW,
  'SIEMENS DICOM': SIEMENS_DICOM,
  'SIEMENS DLR.01': SIEMENS_DLR_01,
  'SIEMENS ISI': SIEMENS_ISI,
  'SIEMENS MED DISPLAY': SIEMENS_MED_DISPLAY,
  'SIEMENS MED HG': SIEMENS_MED_HG,
  'SIEMENS MED MG': SIEMENS_MED_MG,
  'SIEMENS MED': SIEMENS_MED,
  'SIEMENS MEDCOM HEADER': SIEMENS_MEDCOM_HEADER,
  'SIEMENS MR VA0  COAD': SIEMENS_MR_VA0__COAD,
  'SIEMENS MEDCOM HEADER2': SIEMENS_MEDCOM_HEADER2,
  'SIEMENS MEDCOM OOG': SIEMENS_MEDCOM_OOG,
  'SIEMENS MR VA0  GEN': SIEMENS_MR_VA0__GEN,
  'SIEMENS MR VA0  RAW': SIEMENS_MR_VA0__RAW,
  'SIEMENS NUMARIS II': SIEMENS_NUMARIS_II,
  'SIEMENS RA PLANE A': SIEMENS_RA_PLANE_A,
  'SIEMENS RA PLANE B': SIEMENS_RA_PLANE_B,
  'SIEMENS RIS': SIEMENS_RIS,
  'SIEMENS SMS-AX  ACQ 1.0': SIEMENS_SMS_AX__ACQ_1_0,
  'SIEMENS SMS-AX  ORIGINAL IMAGE INFO 1.0':
      SIEMENS_SMS_AX__ORIGINAL_IMAGE_INFO_1_0,
  'SIEMENS SMS-AX  QUANT 1.0': SIEMENS_SMS_AX__QUANT_1_0,
  'SIEMENS SMS-AX  VIEW 1.0': SIEMENS_SMS_AX__VIEW_1_0,
  'SIENET': SIENET,
  'SPI RELEASE 1': SPI_RELEASE_1,
  'SPI': SPI,
  'SPI-P Release 1': SPI_P_Release_1,
  'SPI-P Release 1;1': SPI_P_Release_1_1,
  'SPI-P Release 1;2': SPI_P_Release_1_2,
  'SPI-P Release 1;3': SPI_P_Release_1_3,
  'SPI-P Release 2;1': SPI_P_Release_2_1,
  'SPI-P-GV-CT Release 1': SPI_P_GV_CT_Release_1,
  'SPI-P-PCR Release 2': SPI_P_PCR_Release_2,
  'SPI-P-Private-CWS Release 1': SPI_P_Private_CWS_Release_1,
  'SPI-P-Private-DCI Release 1': SPI_P_Private_DCI_Release_1,
  'SPI-P-Private_CDS Release 1': SPI_P_Private_CDS_Release_1,
  'SPI-P-Private_ICS Release 1': SPI_P_Private_ICS_Release_1,
  'SPI-P-Private_ICS Release 1;1': SPI_P_Private_ICS_Release_1_1,
  'SPI-P-Private_ICS Release 1;2': SPI_P_Private_ICS_Release_1_2,
  'SPI-P-Private_ICS Release 1;3': SPI_P_Private_ICS_Release_1_3,
  'SPI-P-Private_ICS Release 1;4': SPI_P_Private_ICS_Release_1_4,
  'SPI-P-Private_ICS Release 1;5': SPI_P_Private_ICS_Release_1_5,
  'SPI-P-XSB-DCI Release 1': SPI_P_XSB_DCI_Release_1,
  'Silhouette Annot V1.0': Silhouette_Annot_V1_0,
  'Silhouette Graphics Export V1.0': Silhouette_Graphics_Export_V1_0,
  'Silhouette Line V1.0': Silhouette_Line_V1_0,
  'Silhouette ROI V1.0': Silhouette_ROI_V1_0,
  'Silhouette Sequence Ids V1.0': Silhouette_Sequence_Ids_V1_0,
  'Silhouette V1.0': Silhouette_V1_0,
  'SONOWAND AS': SONOWAND_AS,
  'TOSHIBA_MEC_1.0': TOSHIBA_MEC_1_0,
  'TOSHIBA_MEC_CT_1.0': TOSHIBA_MEC_CT_1_0,
  'ACUSON:1.2.840.113680.1.0:0910': ACUSON_1_2_840_113680_1_0_0910,
  'ACUSON:1.2.840.113680.1.0:7f10': ACUSON_1_2_840_113680_1_0_7f10,
  'AGFA-AG_HPState': AGFA_AG_HPState,
  'ACUSON:1.2.840.113680.1.0:7ffe': ACUSON_1_2_840_113680_1_0_7ffe,
  'AgilityRuntime': AgilityRuntime,
  'AGFA_ADC_Compact': AGFA_ADC_Compact,
  'Agfa ADC NX': Agfa_ADC_NX,
  'AGFA PACS Archive Mirroring 1.0': AGFA_PACS_Archive_Mirroring_1_0,
  'MITRA PRESENTATION 1.0': MITRA_PRESENTATION_1_0,
  'MITRA OBJECT DOCUMENT 1.0': MITRA_OBJECT_DOCUMENT_1_0,
  'MITRA MARKUP 1.0': MITRA_MARKUP_1_0,
  'MITRA LINKED ATTRIBUTES 1.0': MITRA_LINKED_ATTRIBUTES_1_0,
  'MITRA OBJECT UTF8 ATTRIBUTES 1.0': MITRA_OBJECT_UTF8_ATTRIBUTES_1_0,
  'MITRA OBJECT ATTRIBUTES 1.0': MITRA_OBJECT_ATTRIBUTES_1_0,
  'AgilityOverlay': AgilityOverlay,
  'AGFA KOSD 1.0': AGFA_KOSD_1_0,
  'agfa/displayableImages': agfa_displayableImages,
  'agfa/xeroverse': agfa_xeroverse,
  'Camtronics image level data': Camtronics_image_level_data,
  'QCA Results': QCA_Results,
  'GEMS_PETD_01': GEMS_PETD_01,
  'GEMS_DL_PATNT_01': GEMS_DL_PATNT_01,
  'GEMS_DL_STUDY_01': GEMS_DL_STUDY_01,
  'GEMS_DL_SERIES_01': GEMS_DL_SERIES_01,
  'GEMS_DL_IMG_01': GEMS_DL_IMG_01,
  'GEMS_XR3DCAL_01': GEMS_XR3DCAL_01,
  'Mayo/IBM Archive Project': Mayo_IBM_Archive_Project,
  'GEMS_3D_INTVL_01': GEMS_3D_INTVL_01,
  'GEMS_DL_FRAME_01': GEMS_DL_FRAME_01,
  'GEMS_ADWSoft_DPO1': GEMS_ADWSoft_DPO1,
  'GEMS_AWSoft_SB1': GEMS_AWSoft_SB1,
  'GEMS_AWSOFT_CD1': GEMS_AWSOFT_CD1,
  'GEMS_HELIOS_01': GEMS_HELIOS_01,
  'GEMS_3DSTATE_001': GEMS_3DSTATE_001,
  'GEMS_IQTB_IDEN_47': GEMS_IQTB_IDEN_47,
  'GEMS_CT_HINO_01': GEMS_CT_HINO_01,
  'GEIIS': GEIIS,
  'GEMS_CT_VES_01': GEMS_CT_VES_01,
  'AMI Annotations_01': AMI_Annotations_01,
  'AMI Annotations_02': AMI_Annotations_02,
  'AMI Sequence Annotations_01': AMI_Sequence_Annotations_01,
  'AMI Sequence Annotations_02': AMI_Sequence_Annotations_02,
  'GEMS_CT_CARDIAC_001': GEMS_CT_CARDIAC_001,
  'AMI Sequence AnnotElements_01': AMI_Sequence_AnnotElements_01,
  'AMI ImageTransform_01': AMI_ImageTransform_01,
  'AMI ImageContextExt_01': AMI_ImageContextExt_01,
  'Applicare/RadWorks/Version 5.0': Applicare_RadWorks_Version_5_0,
  'Applicare/RadWorks/Version 6.0/Summary':
      Applicare_RadWorks_Version_6_0_Summary,
  'http://www.gemedicalsystems.com/it_solutions/rad_pacs/':
      http___www_gemedicalsystems_com_it_solutions_rad_pacs_,
  'Applicare/Print/Version 5.1': Applicare_Print_Version_5_1,
  'Applicare/RadWorks/Version 6.0': Applicare_RadWorks_Version_6_0,
  'GEIIS PACS': GEIIS_PACS,
  'GEMS_GDXE_FALCON_04': GEMS_GDXE_FALCON_04,
  'GEMS_FALCON_03': GEMS_FALCON_03,
  'GEMS_SEND_02': GEMS_SEND_02,
  'GEMS_GDXE_ATHENAV2_INTERNAL_USE': GEMS_GDXE_ATHENAV2_INTERNAL_USE,
  'GEMS_Ultrasound_ImageGroup_001': GEMS_Ultrasound_ImageGroup_001,
  'GEMS_Ultrasound_ExamGroup_001': GEMS_Ultrasound_ExamGroup_001,
  'GEMS_Ultrasound_MovieGroup_001': GEMS_Ultrasound_MovieGroup_001,
  'KRETZ_US': KRETZ_US,
  'QUASAR_INTERNAL_USE': QUASAR_INTERNAL_USE,
  'APEX_PRIVATE': APEX_PRIVATE,
  'GEMS_XELPRV_01': GEMS_XELPRV_01,
  'REPORT_FROM_APP': REPORT_FROM_APP,
  'GEMS_VXTL_USERDATA_01': GEMS_VXTL_USERDATA_01,
  'DL_INTERNAL_USE': DL_INTERNAL_USE,
  'GEMS_LUNAR_RAW': GEMS_LUNAR_RAW,
  'GE_GROUP': GE_GROUP,
  'GEMS_IT_US_REPORT': GEMS_IT_US_REPORT,
  'Applicare/Workflow/Version 1.0': Applicare_Workflow_Version_1_0,
  'GEHC_CT_ADVAPP_001': GEHC_CT_ADVAPP_001,
  'GE LUT Asymmetry Parameter': GE_LUT_Asymmetry_Parameter,
  'Applicare/Centricity Radiology Web/Version 1.0':
      Applicare_Centricity_Radiology_Web_Version_1_0,
  'Applicare/Centricity Radiology Web/Version 2.0':
      Applicare_Centricity_Radiology_Web_Version_2_0,
  'GEMS-IT/Centricity RA600/7.0': GEMS_IT_Centricity_RA600_7_0,
  'AMI StudyExtensions_01': AMI_StudyExtensions_01,
  'RadWorksTBR': RadWorksTBR,
  'Applicare/RadStore/Version 1.0': Applicare_RadStore_Version_1_0,
  'http://www.gemedicalsystems.com/it_solutions/orthoview/2.1':
      http___www_gemedicalsystems_com_it_solutions_orthoview_2_1,
  'http://www.gemedicalsystems.com/it_solutions/bamwallthickness/1.0':
      http___www_gemedicalsystems_com_it_solutions_bamwallthickness_1_0,
  'AMI ImageContext_01': AMI_ImageContext_01,
  'GEMS_FUNCTOOL_01': GEMS_FUNCTOOL_01,
  'Harmony R1.0': Harmony_R1_0,
  'Harmony R1.0 C2': Harmony_R1_0_C2,
  'Harmony R1.0 C3': Harmony_R1_0_C3,
  'Harmony R2.0': Harmony_R2_0,
  'Hologic': Hologic,
  'LODOX_STATSCAN': LODOX_STATSCAN,
  'SCHICK TECHNOLOGIES - Change List Creator ID':
      SCHICK_TECHNOLOGIES___Change_List_Creator_ID,
  'SCHICK TECHNOLOGIES - Note List Creator ID':
      SCHICK_TECHNOLOGIES___Note_List_Creator_ID,
  'SCHICK TECHNOLOGIES - Change Item Creator ID':
      SCHICK_TECHNOLOGIES___Change_Item_Creator_ID,
  'SCHICK TECHNOLOGIES - Image Security Creator ID':
      SCHICK_TECHNOLOGIES___Image_Security_Creator_ID,
  '2.16.840.1.114059.1.1.6.1.50.1': Uid_2_16_840_1_114059_1_1_6_1_50_1,
  'STENTOR': STENTOR,
  'MMCPrivate': MMCPrivate,
  'Canon Inc.': Canon_Inc_,
  'SECTRA_Ident_01': SECTRA_Ident_01,
  'SECTRA_ImageInfo_01': SECTRA_ImageInfo_01,
  'SECTRA_OverlayInfo_01': SECTRA_OverlayInfo_01,
  'BioPri': BioPri,
  'Silhouette VRS 3.0': Silhouette_VRS_3_0,
  'ADAC_IMG': ADAC_IMG,
  'Hipaa Private Creator': Hipaa_Private_Creator,
  'LORAD Selenia': LORAD_Selenia,
  'HOLOGIC, Inc.': HOLOGIC__Inc_,
  '1.2.840.113663.1': Uid_1_2_840_113663_1,
  'MeVis BreastCare': MeVis_BreastCare,
  'Viewing Protocol': Viewing_Protocol,
  'Mortara_Inc': Mortara_Inc,
  'SEGAMI_HEADER': SEGAMI_HEADER,
  'SEGAMI MIML': SEGAMI_MIML,
  'SEGAMI__PAGE': SEGAMI__PAGE,
  'SEGAMI__MEMO': SEGAMI__MEMO,
  'MedIns HP Extensions': MedIns_HP_Extensions,
  'MEDIFACE': MEDIFACE,
  'Image (ID, Version, Size, Dump, GUID)':
      Image__ID__Version__Size__Dump__GUID_,
  'ObjectModel (ID, Version, Place, PlaceDescription)':
      ObjectModel__ID__Version__Place__PlaceDescription_,
  'INFINITT_FMX': INFINITT_FMX,
  'BrainLAB_Conversion': BrainLAB_Conversion,
  'BrainLAB_PatientSetup': BrainLAB_PatientSetup,
  'BrainLAB_BeamProfile': BrainLAB_BeamProfile,
  'V1': V1,
  'Voxar 2.16.124.113543.6003.1999.12.20.12.5.0':
      Voxar_2_16_124_113543_6003_1999_12_20_12_5_0,
  'Kodak Image Information': Kodak_Image_Information,
  'NQLeft': NQLeft,
  'MAROTECH Inc.': MAROTECH_Inc_,
  'BRIT Systems, Inc.': BRIT_Systems__Inc_,
  'MDS NORDION OTP ANATOMY MODELLING': MDS_NORDION_OTP_ANATOMY_MODELLING,
  'Imaging Dynamics Company Ltd.': Imaging_Dynamics_Company_Ltd_,
  'Sound Technologies': Sound_Technologies,
  'A.L.I. Technologies, Inc.': A_L_I__Technologies__Inc_,
  'NUD_PRIVATE': NUD_PRIVATE,
  'IDEXX': IDEXX,
  'WG12 Supplement 43': WG12_Supplement_43,
  'HMC - CT - ID': HMC___CT___ID,
  'SET WINDOW': SET_WINDOW,
  'Vital Images SW 3.4': Vital_Images_SW_3_4,
  'PI Private Block (0781:3000 - 0781:30FF)':
      PI_Private_Block__0781_3000___0781_30FF_,
  'Riverain Medical': Riverain_Medical,
  'INTELERAD MEDICAL SYSTEMS INTELEVIEWER':
      INTELERAD_MEDICAL_SYSTEMS_INTELEVIEWER,
  'DR Systems, Inc.': DR_Systems__Inc_,
  'ETIAM DICOMDIR': ETIAM_DICOMDIR,
  'TERARECON AQUARIUS': TERARECON_AQUARIUS,
  'EMAGEON STUDY HOME': EMAGEON_STUDY_HOME,
  'EMAGEON JPEG2K INFO': EMAGEON_JPEG2K_INFO,
  'RadWorksMarconi': RadWorksMarconi,
  'MeVis eatDicom': MeVis_eatDicom,
  'MeVis eD: Timepoint Information': MeVis_eD__Timepoint_Information,
  'MeVis eD: Absolute Temporal Positions':
      MeVis_eD__Absolute_Temporal_Positions,
  'MeVis eD: Geometry Information': MeVis_eD__Geometry_Information,
  'MeVis eD: Slice Information': MeVis_eD__Slice_Information,
  'ShowcaseAppearance': ShowcaseAppearance,
  'NQHeader': NQHeader,
  'NQRight': NQRight,
  'VEPRO VIF 3.0 DATA': VEPRO_VIF_3_0_DATA,
  'VEPRO VIM 5.0 DATA': VEPRO_VIM_5_0_DATA,
  'VEPRO BROKER 1.0': VEPRO_BROKER_1_0,
  'VEPRO BROKER 1.0 DATA REPLACE': VEPRO_BROKER_1_0_DATA_REPLACE,
  'VEPRO DICOM TRANSFER 1.0': VEPRO_DICOM_TRANSFER_1_0,
  'VEPRO DICOM RECEIVE DATA 1.0': VEPRO_DICOM_RECEIVE_DATA_1_0,
  'KONICA1.0': KONICA1_0,
  'CTP': CTP,
  'dcm4che/archive': dcm4che_archive,
  'IMS s.r.l. Biopsy Private Code': IMS_s_r_l__Biopsy_Private_Code,
  'IMS s.r.l. Mammography Private Code': IMS_s_r_l__Mammography_Private_Code,
  'DZDICOM 4.3.0': DZDICOM_4_3_0,
  'FOEM 1.0': FOEM_1_0,
  'Visus Change': Visus_Change,
  'SYNARC_1.0': SYNARC_1_0,
  'PixelMed Publishing': PixelMed_Publishing,
  'METAEMOTION GINKGO': METAEMOTION_GINKGO,
  'METAEMOTION GINKGO RETINAL': METAEMOTION_GINKGO_RETINAL,
  'PMOD_1': PMOD_1,
  'PMOD_GENPET': PMOD_GENPET,
  'ULTRAVISUAL_TAG_SET1': ULTRAVISUAL_TAG_SET1,
  'MATAKINA_10': MATAKINA_10,
  'PM': PM,
  'Biospace Med : EOS Tag': Biospace_Med___EOS_Tag,
  'PRIVATE_CODE_STRING_0019': PRIVATE_CODE_STRING_0019,
  'PRIVATE_CODE_STRING_0021': PRIVATE_CODE_STRING_0021,
  'PRIVATE_CODE_STRING_1001': PRIVATE_CODE_STRING_1001,
  'CAD Sciences': CAD_Sciences,
  'PRIVATE_CODE_STRING_1003': PRIVATE_CODE_STRING_1003,
  'PRIVATE_CODE_STRING_3007': PRIVATE_CODE_STRING_3007,
  'PRIVATE_CODE_STRING_300B': PRIVATE_CODE_STRING_300B,
  'INSTRU_PRIVATE_IDENT_CODE': INSTRU_PRIVATE_IDENT_CODE,
  'SCANORA_PRIVATE_IDENT_CODE': SCANORA_PRIVATE_IDENT_CODE,
  'NNT': NNT,
  'iCAD PK': iCAD_PK,
  'iCAD PK Study': iCAD_PK_Study,
  'TomTec': TomTec,
  'CARESTREAM IMAGE INFORMATION': CARESTREAM_IMAGE_INFORMATION,
  'Carestream Health TIFF': Carestream_Health_TIFF,
  'RamSoft File Kind Identifier': RamSoft_File_Kind_Identifier,
  'RamSoft Custom Report Identifier': RamSoft_Custom_Report_Identifier,
  'RamSoft Race Identifier': RamSoft_Race_Identifier,
  'MDDX': MDDX,
  'QTUltrasound': QTUltrasound,
  'BioscanMedisoScivisNanoSPECT': BioscanMedisoScivisNanoSPECT,
  'MEDISO-1': MEDISO_1,
  'SCIVIS-1': SCIVIS_1,
  'Brainlab-S9-History': Brainlab_S9_History,
  'Brainlab-S32-SO': Brainlab_S32_SO,
  'Brainlab-S23-ProjectiveFusion': Brainlab_S23_ProjectiveFusion,
  'PHILIPS MR/PART 12': PHILIPS_MR_PART_12,
  'PHILIPS MR/PART 7': PHILIPS_MR_PART_7,
  'SPI-P-CTBE Release 1': SPI_P_CTBE_Release_1,
  'SPI-P-Private-DiDi Release 1': SPI_P_Private_DiDi_Release_1,
  'SPI-P-XSB-VISUB Release 1': SPI_P_XSB_VISUB_Release_1,
  'PHILIPS MR/PART 6': PHILIPS_MR_PART_6,
  'SPI-P-CTBE-Private Release 1': SPI_P_CTBE_Private_Release_1,
  'PMS-THORA-5.1': PMS_THORA_5_1,
  'Philips PET Private Group': Philips_PET_Private_Group,
  'Philips Imaging DD 124': Philips_Imaging_DD_124,
  'Philips Imaging DD 129': Philips_Imaging_DD_129,
  'Philips Imaging DD 002': Philips_Imaging_DD_002,
  'Philips X-ray Imaging DD 001': Philips_X_ray_Imaging_DD_001,
  'Philips MR Imaging DD 003': Philips_MR_Imaging_DD_003,
  'Philips MR Imaging DD 004': Philips_MR_Imaging_DD_004,
  'Philips MR Imaging DD 002': Philips_MR_Imaging_DD_002,
  'Philips EV Imaging DD 022': Philips_EV_Imaging_DD_022,
  'Philips RAD Imaging DD 001': Philips_RAD_Imaging_DD_001,
  'Philips RAD Imaging DD 097': Philips_RAD_Imaging_DD_097,
  'Philips US Imaging DD 033': Philips_US_Imaging_DD_033,
  'Philips US Imaging DD 066': Philips_US_Imaging_DD_066,
  'Philips US Imaging DD 109': Philips_US_Imaging_DD_109,
  'Philips US Imaging DD 034': Philips_US_Imaging_DD_034,
  'Philips US Imaging DD 035': Philips_US_Imaging_DD_035,
  'Philips US Imaging DD 038': Philips_US_Imaging_DD_038,
  'Philips US Imaging DD 039': Philips_US_Imaging_DD_039,
  'Philips US Imaging DD 040': Philips_US_Imaging_DD_040,
  'Philips US Imaging DD 041': Philips_US_Imaging_DD_041,
  'Philips US Imaging DD 048': Philips_US_Imaging_DD_048,
  'Philips US Imaging DD 113': Philips_US_Imaging_DD_113,
  'Philips US Imaging DD 037': Philips_US_Imaging_DD_037,
  'Philips US Imaging DD 017': Philips_US_Imaging_DD_017,
  'Philips US Imaging DD 043': Philips_US_Imaging_DD_043,
  'Philips US Imaging DD 021': Philips_US_Imaging_DD_021,
  'Philips US Imaging DD 065': Philips_US_Imaging_DD_065,
  'Philips US Imaging DD 036': Philips_US_Imaging_DD_036,
  'Philips US Imaging DD 042': Philips_US_Imaging_DD_042,
  'Philips US Imaging DD 046': Philips_US_Imaging_DD_046,
  'Philips US Imaging DD 023': Philips_US_Imaging_DD_023,
  'Philips US Imaging DD 045': Philips_US_Imaging_DD_045,
  'Philips Imaging DD 067': Philips_Imaging_DD_067,
  'Philips Imaging DD 070': Philips_Imaging_DD_070,
  'Philips Imaging DD 065': Philips_Imaging_DD_065,
  'Philips Imaging DD 073': Philips_Imaging_DD_073,
  'Philips NM Private Group': Philips_NM_Private_Group,
  'PHILIPS NM -Private': PHILIPS_NM__Private,
  'PHILIPS XCT -Private': PHILIPS_XCT__Private,
  'Picker MR Private Group': Picker_MR_Private_Group,
  'SIEMENS SYNGO INSTANCE MANIFEST': SIEMENS_SYNGO_INSTANCE_MANIFEST,
  'SIEMENS MED NM': SIEMENS_MED_NM,
  'SIEMENS SYNGO INDEX SERVICE': SIEMENS_SYNGO_INDEX_SERVICE,
  'SIEMENS AX INSPACE_EP': SIEMENS_AX_INSPACE_EP,
  'SIEMENS MR DATAMAPPING ATTRIBUTES': SIEMENS_MR_DATAMAPPING_ATTRIBUTES,
  'ESOFT_DICOM_ECAT_OWNERCODE': ESOFT_DICOM_ECAT_OWNERCODE,
  'Siemens: Thorax/Multix FD Version': Siemens__Thorax_Multix_FD_Version,
  'SIEMENS_FLCOMPACT_VA01A_PROC': SIEMENS_FLCOMPACT_VA01A_PROC,
  'SIEMENS DFR.01 ORIGINAL': SIEMENS_DFR_01_ORIGINAL,
  'SIEMENS DFR.01 MANIPULATED': SIEMENS_DFR_01_MANIPULATED,
  'SIEMENS MED SP DXMG WH AWS 1': SIEMENS_MED_SP_DXMG_WH_AWS_1,
  'SIEMENS Selma': SIEMENS_Selma,
  'SIEMENS SIENET': SIEMENS_SIENET,
  'SIEMENS MED SMS USG ANTARES': SIEMENS_MED_SMS_USG_ANTARES,
  'SIEMENS SYNGO VOLUME': SIEMENS_SYNGO_VOLUME,
  'Siemens Ultrasound Miscellaneous': Siemens_Ultrasound_Miscellaneous,
  'Siemens: Thorax/Multix FD Lab Settings':
      Siemens__Thorax_Multix_FD_Lab_Settings,
  'SIEMENS MED SMS USG S2000': SIEMENS_MED_SMS_USG_S2000,
  'SIEMENS MED ECAT FILE INFO': SIEMENS_MED_ECAT_FILE_INFO,
  'Siemens: Thorax/Multix FD Post Processing':
      Siemens__Thorax_Multix_FD_Post_Processing,
  'KINETDX_GRAPHICS': KINETDX_GRAPHICS,
  'KINETDX': KINETDX,
  'syngoDynamics': syngoDynamics,
  'Siemens: Thorax/Multix FD Image Stamp':
      Siemens__Thorax_Multix_FD_Image_Stamp,
  'Siemens: Thorax/Multix FD Raw Image Settings':
      Siemens__Thorax_Multix_FD_Raw_Image_Settings,
  'SIEMENS SYNGO ENHANCED IDATASET API': SIEMENS_SYNGO_ENHANCED_IDATASET_API,
  'SIEMENS SYNGO FUNCTION ASSIGNMENT': SIEMENS_SYNGO_FUNCTION_ASSIGNMENT,
  'SHS MagicView 300': SHS_MagicView_300,
  'SIEMENS MED MAMMO': SIEMENS_MED_MAMMO,
  'SIEMENS MED DISPLAY 0000': SIEMENS_MED_DISPLAY_0000,
  'SIEMENS MED DISPLAY 0001': SIEMENS_MED_DISPLAY_0001,
  'SIEMENS SYNGO TIME POINT SERVICE': SIEMENS_SYNGO_TIME_POINT_SERVICE,
  'SIEMENS SYNGO ADVANCED PRESENTATION': SIEMENS_SYNGO_ADVANCED_PRESENTATION,
  'SIEMENS SYNGO FRAME SET': SIEMENS_SYNGO_FRAME_SET,
  'SIEMENS SYNGO PRINT SERVICE': SIEMENS_SYNGO_PRINT_SERVICE,
  'SIEMENS IKM CKS LUNGCAD BMK': SIEMENS_IKM_CKS_LUNGCAD_BMK,
  'SIEMENS IKM CKS CXRCAD FINDINGS': SIEMENS_IKM_CKS_CXRCAD_FINDINGS,
  'SIEMENS SYNGO SOP CLASS PACKING': SIEMENS_SYNGO_SOP_CLASS_PACKING,
  'SIEMENS CSA ENVELOPE': SIEMENS_CSA_ENVELOPE,
  'SIEMENS CSA REPORT': SIEMENS_CSA_REPORT,
  'SIEMENS SYNGO WORKFLOW': SIEMENS_SYNGO_WORKFLOW,
  'SIEMENS MI RWVM SUV': SIEMENS_MI_RWVM_SUV,
  'SIEMENS WH SR 1.0': SIEMENS_WH_SR_1_0,
  'SIEMENS MED PT': SIEMENS_MED_PT,
  'SIEMENS SYNGO REGISTRATION': SIEMENS_SYNGO_REGISTRATION,
  'SIEMENS SYNGO OBJECT GRAPHICS': SIEMENS_SYNGO_OBJECT_GRAPHICS,
  'SIEMENS MED PT WAVEFORM': SIEMENS_MED_PT_WAVEFORM,
  'SIEMENS SYNGO LAYOUT PROTOCOL': SIEMENS_SYNGO_LAYOUT_PROTOCOL,
  'SIEMENS SYNGO EVIDENCE DOCUMENT DATA': SIEMENS_SYNGO_EVIDENCE_DOCUMENT_DATA,
  'syngoDynamics_Reporting': syngoDynamics_Reporting,
  'SIEMENS MR N3D': SIEMENS_MR_N3D,
  'SIEMENS SYNGO ENCAPSULATED DOCUMENT DATA':
      SIEMENS_SYNGO_ENCAPSULATED_DOCUMENT_DATA,
  'SIEMENS SYNGO 3D FUSION MATRIX': SIEMENS_SYNGO_3D_FUSION_MATRIX,
  'SIEMENS Ultrasound SC2000': SIEMENS_Ultrasound_SC2000,
  'SIEMENS SYNGO DATA PADDING': SIEMENS_SYNGO_DATA_PADDING,
  'SIEMENS MR HEADER': SIEMENS_MR_HEADER,
  'SIEMENS SERIES SHADOW ATTRIBUTES': SIEMENS_SERIES_SHADOW_ATTRIBUTES,
  'SIEMENS IMAGE SHADOW ATTRIBUTES': SIEMENS_IMAGE_SHADOW_ATTRIBUTES,
  'SIEMENS MR IMA': SIEMENS_MR_IMA,
  'SIEMENS MR PHOENIX ATTRIBUTES': SIEMENS_MR_PHOENIX_ATTRIBUTES,
  'SIEMENS MR SDS 01': SIEMENS_MR_SDS_01,
  'SIEMENS MR MRS 05': SIEMENS_MR_MRS_05,
  'SIEMENS MR EXTRACTED CSA HEADER': SIEMENS_MR_EXTRACTED_CSA_HEADER,
  'SIEMENS MR SDI 02': SIEMENS_MR_SDI_02,
  'SIEMENS MR CM 03': SIEMENS_MR_CM_03,
  'SIEMENS MR PS 04': SIEMENS_MR_PS_04,
  'SIEMENS MR FOR 06': SIEMENS_MR_FOR_06,
  'SIEMENS CT APPL DATASET': SIEMENS_CT_APPL_DATASET,
  'SIEMENS CT APPL EVIDENCEDOCUMENT': SIEMENS_CT_APPL_EVIDENCEDOCUMENT,
  'SIEMENS CT APPL MEASUREMENT': SIEMENS_CT_APPL_MEASUREMENT,
  'SIEMENS CT APPL PRESENTATION': SIEMENS_CT_APPL_PRESENTATION,
  'SIEMENS CT APPL TMP DATAMODEL': SIEMENS_CT_APPL_TMP_DATAMODEL,
  'SIEMENS MED SMS USG ANTARES 3D VOLUME':
      SIEMENS_MED_SMS_USG_ANTARES_3D_VOLUME,
  'SIEMENS MED SMS USG S2000 3D VOLUME': SIEMENS_MED_SMS_USG_S2000_3D_VOLUME,
  'SIEMENS MED OCS BEAM DISPLAY INFO': SIEMENS_MED_OCS_BEAM_DISPLAY_INFO,
  'SIEMENS MED OCS PUBLIC RT PLAN ATTRIBUTES':
      SIEMENS_MED_OCS_PUBLIC_RT_PLAN_ATTRIBUTES,
  'SIEMENS MED OCS SS VERSION INFO': SIEMENS_MED_OCS_SS_VERSION_INFO,
  'BioPri3D': BioPri3D,
  'PMI Private Calibration Module Version 2.0':
      PMI_Private_Calibration_Module_Version_2_0,
  'POLYTRON-SMS 2.5': POLYTRON_SMS_2_5,
  'SIEMENS MED SYNGO RT': SIEMENS_MED_SYNGO_RT,
  'SIEMENS SYNGO ULTRA-SOUND TOYON DATA STREAMING':
      SIEMENS_SYNGO_ULTRA_SOUND_TOYON_DATA_STREAMING,
  'SIEMENS Ultrasound S2000': SIEMENS_Ultrasound_S2000,
  'SMIL_PB79': SMIL_PB79,
  'SMIO_PB7B': SMIO_PB7B,
  'SMIO_PB7D': SMIO_PB7D,
  'TOSHIBA_MEC_OT3': TOSHIBA_MEC_OT3,
  'TOSHIBA MDW NON-IMAGE': TOSHIBA_MDW_NON_IMAGE,
  'TOSHIBA MDW HEADER': TOSHIBA_MDW_HEADER,
  'TOSHIBA COMAPL HEADER': TOSHIBA_COMAPL_HEADER,
  'TOSHIBA COMAPL OOG': TOSHIBA_COMAPL_OOG,
  'PMTF INFORMATION DATA': PMTF_INFORMATION_DATA,
  'TOSHIBA_MEC_CT3': TOSHIBA_MEC_CT3,
  'TOSHIBA ENCRYPTED SR DATA': TOSHIBA_ENCRYPTED_SR_DATA,
  'TOSHIBA_SR': TOSHIBA_SR,
  'TOSHIBA_MEC_XA3': TOSHIBA_MEC_XA3,
  'GE_YMS_NJ001': GE_YMS_NJ001,
  'GEMS_PATI_01': GEMS_PATI_01,
  'GEMS_CT_FLRO_01': GEMS_CT_FLRO_01,
  'GEMS_0039': GEMS_0039,
  'GEMS_HINO_CT_01': GEMS_HINO_CT_01,
  'BrainWave: 1.2.840.113819.3': BrainWave__1_2_840_113819_3,
  'GEMS_MR_RAW_01': GEMS_MR_RAW_01,
  'TOSHIBA_MEC_MR3': TOSHIBA_MEC_MR3
};
